# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# IP: ip/blk_parrotproper_1/blk_parrotproper.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_parrotproper || ORIG_REF_NAME==blk_parrotproper} -quiet] -quiet
